trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Validate
  jobs:
  - job: Validate
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '0.12.3'
    - task: CmdLine@2
      displayName: 'Initialise terraform with local backend'
      inputs:
        script: 'terraform init -backend=false input=false'
    - task: CmdLine@2
      displayName: 'Validate Terraform templates via plan'
      inputs:
        script: 'terraform plan'

- stage: Development
  jobs:
  - deployment: deploy
    environment: Development
    strategy:
     runOnce:
      deploy:
        steps:
        - task: CmdLine@2
          inputs:
            script: 'echo hello world'

- stage: Production
  jobs:
  - deployment: deploy
    environment: Production
    strategy:
     runOnce:
      deploy:
        steps:
        - task: CmdLine@2
          inputs:
            script: 'echo hello world'
