trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Validate
  jobs:
  - job: Validate
    steps:
    - task: CmdLine@2
      inputs:
        script: 'install terraform here'

- stage: Development
  jobs:
  - job: Deploy
    steps:
    - task: CmdLine@2
      inputs:
        script: 'echo hello world'

- stage: Production
  jobs:
  - deployment: deploy
    environment: Production
    strategy:
     runOnce:
      deploy:
        steps:
        - task: CmdLine@2
          inputs:
            script: 'echo hello world'
